#!/bin/bash 

bashrc_custom=". $HOME/.bashrc_custom"

bashrc_init_before=$(cat $HOME/.bashrc 2> /dev/null | grep "$bashrc_custom")

if [ "$profile_init_before" == "" ]
then
  echo $profile_custom >> $HOME/.profile
fi

if [ $SHELL == "/bin/bash" ] && [ "$bashrc_init_before" == "" ]
then
  echo $bashrc_custom >> $HOME/.bashrc
fi
